# -*- coding: utf-8 -*-
"""AI4I 2020 Predictive Maintenance Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ud0OVICwIoObpEPSQ3xLezMgTMgQfR13

# **AI4I 2020 PREDICTIVE MAINTENANCE PROJECT**
"""

!pip install pandas numpy
!pip install scikit-learn
!pip install xgboost
!pip install imbalanced-learn
!pip install matplotlib seaborn
!pip install xgboost imbalanced-learn seaborn -q
import pandas as pd
import numpy as np
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)
from xgboost import XGBClassifier
from imblearn.combine import SMOTETomek
import matplotlib.pyplot as plt
import seaborn as sns

"""LOAD DATASET

"""

uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)
print("\nDataset Shape:")
print(df.shape)

"""CLEAN COLUMN NAMES

"""

df.columns = [
    col.replace(" ", "_")
       .replace("[", "")
       .replace("]", "")
       .replace("/", "_")
    for col in df.columns
]
print("\nColumns:")
print(df.columns.tolist())

"""REMOVE UNNECESSARY COLUMNS

"""

df.drop(
    columns=[
        "UDI",
        "Product_ID",
        "TWF",
        "HDF",
        "PWF",
        "OSF",
        "RNF"
    ],
    inplace=True
)

"""ENCODE MACHINE TYPE

"""

le = LabelEncoder()
df["Type"] = le.fit_transform(df["Type"])

"""FEATURE ENGINEERING

"""

df["Temp_Diff"] = (
    df["Process_temperature_K"]
    - df["Air_temperature_K"]
)
df["Power"] = (
    df["Torque_Nm"]
    * df["Rotational_speed_rpm"]
)
df["Wear_Rate"] = (
    df["Tool_wear_min"]
    /
    (df["Rotational_speed_rpm"] + 1)
)
df["Thermal_Load"] = (
    df["Process_temperature_K"]
    * df["Torque_Nm"]
)
df["Mechanical_Stress"] = (
    df["Torque_Nm"]
    * df["Tool_wear_min"]
)

"""TARGET

"""

X = df.drop("Machine_failure", axis=1)
y = df["Machine_failure"]
print("\nOriginal Class Distribution")
print(y.value_counts())

"""BALANCE DATASET

"""

smote = SMOTETomek(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
print("\nBalanced Class Distribution")
print(pd.Series(y_resampled).value_counts())

"""TRAIN TEST SPLIT, MODEL AND IT'S TRAINING"""

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled,
    y_resampled,
    test_size=0.20,
    random_state=42,
    stratify=y_resampled
)
model = XGBClassifier(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    random_state=42
)
print("\nTraining Started...")
model.fit(X_train, y_train)
print("\nTraining Completed")

"""PREDICTIONS AND METRICS"""

y_pred = model.predict(X_test)
accuracy = accuracy_score(
    y_test,
    y_pred
)
print("MODEL ACCURACY")
print(f"{accuracy*100:.2f}%")
print("CLASSIFICATION REPORT")
print(
    classification_report(
        y_test,
        y_pred
    )
)
cm = confusion_matrix(
    y_test,
    y_pred
)
print("\nConfusion Matrix")
print(cm)
plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""FEATURE IMPORTANCE

"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})
importance = importance.sort_values(
    by="Importance",
    ascending=False
)
print("\nFeature Importance")
print(importance)
plt.figure(figsize=(10,6))
sns.barplot(
    data=importance,
    x="Importance",
    y="Feature"
)
plt.title("Feature Importance")
plt.show()

"""SAMPLE MACHINE PREDICTION AND SAME FEATURE ENGINEERING

"""

sample = pd.DataFrame({
    "Type":[1],
    "Air_temperature_K":[298.1],
    "Process_temperature_K":[308.6],
    "Rotational_speed_rpm":[1551],
    "Torque_Nm":[42.8],
    "Tool_wear_min":[50]
})
sample["Temp_Diff"] = (
    sample["Process_temperature_K"]
    - sample["Air_temperature_K"]
)
sample["Power"] = (
    sample["Torque_Nm"]
    * sample["Rotational_speed_rpm"]
)
sample["Wear_Rate"] = (
    sample["Tool_wear_min"]
    /
    (sample["Rotational_speed_rpm"] + 1)
)
sample["Thermal_Load"] = (
    sample["Process_temperature_K"]
    * sample["Torque_Nm"]
)
sample["Mechanical_Stress"] = (
    sample["Torque_Nm"]
    * sample["Tool_wear_min"]
)

"""PREDICT SAMPLE AND ALERT SYSTEM

"""

prediction = model.predict(sample)
probability = model.predict_proba(sample)
failure_probability = probability[0][1] * 100
print("LIVE MACHINE HEALTH CHECK")
if prediction[0] == 1:
    print("⚠ MACHINE FAILURE EXPECTED")
else:
    print("MACHINE HEALTHY")

print(
    f"Failure Probability: {failure_probability:.2f}%"
)
if failure_probability > 80:
    print("\nALERT")
    print("Immediate Maintenance Required")
elif failure_probability > 50:
    print("\n⚠ WARNING")
    print("Schedule Maintenance Soon")
else:
    print("\nSTATUS")
    print("Machine Operating Normally")
print("\nProject Execution Completed Successfully")

"""MACHINE HEALTH DIGITAL TWIN MODULE AND NORMALISE VALUES"""

print("\nGenerating Digital Twin Metrics...")
wear_score = (
    df["Tool_wear_min"]
    /
    df["Tool_wear_min"].max()
) * 100
torque_score = (
    df["Torque_Nm"]
    /
    df["Torque_Nm"].max()
) * 100
thermal_diff = (
    df["Process_temperature_K"]
    -
    df["Air_temperature_K"]
)
thermal_score = (
    thermal_diff
    /
    thermal_diff.max()
) * 100

"""MACHINE HEALTH INDEX AND FAILURE SEVERITY

"""

df["Machine_Health_Index"] = (
    100
    -
    (
        0.40 * wear_score
        +
        0.30 * torque_score
        +
        0.30 * thermal_score
    )
)
df["Machine_Health_Index"] = (
    df["Machine_Health_Index"]
    .clip(0,100)
)
df["Failure_Severity"] = (
    0.35 * wear_score
    +
    0.35 * torque_score
    +
    0.30 * thermal_score
)
df["Failure_Severity"] = (
    df["Failure_Severity"]
    .clip(0,100)
)

"""REMAINING USEFUL LIFE, FAILURE CATEGORY, MAINTENANCE PRIORITY AND FAILURE TYPE LABEL

"""

df["RUL_Hours"] = (
    100
    -
    df["Failure_Severity"]
) * 2
def severity_label(x):
    if x < 30:
        return "LOW"
    elif x < 60:
        return "MEDIUM"
    elif x < 80:
        return "HIGH"
    else:
        return "CRITICAL"
df["Severity_Class"] = (
    df["Failure_Severity"]
    .apply(severity_label)
)
def maintenance_priority(mhi, severity):
    if mhi < 30 or severity > 80:
        return "IMMEDIATE"
    elif mhi < 50:
        return "WITHIN 24 HOURS"
    elif mhi < 70:
        return "WITHIN 7 DAYS"
    else:
        return "NORMAL"
df["Maintenance_Action"] = [
    maintenance_priority(mhi, sev)
    for mhi, sev in zip(
        df["Machine_Health_Index"],
        df["Failure_Severity"]
    )
]
print("\nDigital Twin Metrics Generated")
failure_type = []
for _, row in pd.read_csv(file_name).iterrows():
    if row["TWF"] == 1:
        failure_type.append("Tool Wear Failure")
    elif row["HDF"] == 1:
        failure_type.append("Heat Dissipation Failure")
    elif row["PWF"] == 1:
        failure_type.append("Power Failure")
    elif row["OSF"] == 1:
        failure_type.append("Overstrain Failure")
    elif row["RNF"] == 1:
        failure_type.append("Random Failure")
    else:
        failure_type.append("Healthy")
df["Failure_Type"] = failure_type

"""SHOWING SAMPLE RESULTS

"""

sample_row = df.iloc[0]
print(
    "Machine Health Index:",
    round(sample_row["Machine_Health_Index"],2)
)
print(
    "Failure Severity:",
    round(sample_row["Failure_Severity"],2)
)
print(
    "Remaining Useful Life:",
    round(sample_row["RUL_Hours"],2),
    "Hours"
)
print(
    "Maintenance Action:",
    sample_row["Maintenance_Action"]
)
print(
    "Failure Type:",
    sample_row["Failure_Type"]
)